variable "db_instance_class" {}
variable "dbname" {}
variable "vpc_security_group_ids" {}
variable "db_subnet_group_name" {}
variable "db_engine_version" {}
variable "db_identifier" {}
variable "skip_final_snapshot" {}
variable "multi_az" {}
variable "backup_window" {}
variable "backup_retention_period" {}
variable "final_snapshot_identifier_suffix" {}
